# App title & short title
title: "Netflix Cheatcodes"
shortTitle: "NFCC"

# main contact email for the app
email: "hi@dereknutile.com"

# brief description for the site
description: "Filterable database of Netflix cheat codes."

# one line short description for the site
tagline: ""

# leave empty unless you need to store the mockup in a subfolder
# don't use a trailing slash
baseurl: ""

# library baseurls
fontAwesomeFontBaseUrl: "http://fortawesome.github.io/Font-Awesome/icon/"

# replace with the domain of the mockup
url: "http://netflix-cheatcodes.github.io/"

# site favicon
favicon: "/assets/ico/favicon.png"

# usernames
facebook-username: "dereknutile"
twitter-username: "dereknutile"
gootgle-plus-username: "+dereknutile"

# analytic settings
# google-analytics: "UA-CODE-GOES-HERE"

# Jekyll build settings
markdown: kramdown
permalink: pretty
